name: Build and Release
on: [push]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r RouteMatriXRandomizer_progress_displayer_v0.0.2.zip dist
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "RouteMatriXRandomizer_progress_displayer_v0.0.2.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'v0.0.2'
